## 1. Pandas로 데이터 불러오기

In [9]:
import pandas as pd

pro_end = pd.read_excel('../EDA자료/pro_end.xlsx')
print(pro_end)
pro_end.head()

    Unnamed: 0           기업명    사원수  \
0            0         AB180  101 명
1            1         AB180  101 명
2            2         레몬베이스   63 명
3            3          오토위니   55 명
4            4          페이타랩   68 명
5            5         로보코리아   33 명
6            6         로보코리아   33 명
7            7          한화비전  791 명
8            8         디플래닉스   25 명
9            9            발란   66 명
10          10         헬스피디아    9 명
11          11          플라잉캣    3 명
12          12       월급쟁이부자들   84 명
13          13         에잇퍼센트   55 명
14          14            앤트   19 명
15          15        포스페이스랩   20 명
16          16        포스페이스랩   20 명
17          17        유케이미디어   11 명
18          18           링키스    3 명
19          19        차봇모빌리티   78 명
20          20            카비   23 명
21          21            뽀득  265 명
22          22          리걸테크   27 명
23          23       코넥시오에이치   20 명
24          24  에이치디현대글로벌서비스  528 명
25          25       에디트콜렉티브   15 명
26          26        제이앤피메디   61 명
27          27        제이앤피메디   61 명
28          28        제이앤피메디   61 명
29          29        제이앤피메디   61 명
30          30        잉글리시에그   61 명
31          31        씨앤에이아이   48 명
32          32        인그래디언트    4 명
33          33        에이에프아이   22 명
34          34          티웨이브   21 명
35          35         와이오엘오   37 명
36          36        아레나캐스트    3 명
37          37         컨비니언스   36 명
38          38            쿤텍   81 명
39          39            쿤텍   81 명
40          40           누벤트   18 명
41          41          셀러허브   48 명
42          42          아이트럭   18 명
43          43           컨워스    8 명
44          44         팀블랙버드   23 명
45          45         팀블랙버드   23 명
46          46        델레오코리아   46 명
47          47         옵틱라이프    5 명

                                              주소  \
0          대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17
1          대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17
2         서울 성동구 아차산로 68, (성수동2가) 11층, 12층 레몬베이스
3              서울 강남구 남부순환로 2645, 3층 (도곡동, 한독빌딩)
4                    서울 강남구 영동대로85길 34, (대치동) 6층
5                        서울 강남구 테헤란로25길 7, (역삼동)
6                        서울 강남구 테헤란로25길 7, (역삼동)
7                   경기도 성남시 분당구 판교로319번길 6 (삼평동)
8                 서울 서초구 강남대로 465, 강남 교보타워 B동 4층
9                   대한민국 서울특별시 강남구 테헤란로 217, 10층
10                                        다산로104
11                       서울 강남구 논현로57길 30, (도곡동)
12                   서울 서초구 사임당로 143, (서초동) 201호
13       서울특별시 영등포구 국제금융로2길 17, 13층(여의도동, 씨티플라자)
14                       서울 강남구 논현로75길 16, (역삼동)
15              서울 강남구 테헤란로 147, (역삼동) 3층 위멤버스클럽
16              서울 강남구 테헤란로 147, (역삼동) 3층 위멤버스클럽
17                          서울 종로구 종로 51, (종로2가)
18  서울특별시 강남구 도산대로 145 인우빌딩 4층 408호 (패스트파이브 신사점)
19        대한민국 서울특별시 성동구 연무장7길 11, 플레이스캠프 성수 10층
20         서울 금천구 벚꽃로 244, (가산동) 벽산디지털밸리 5차 301호
21                      서울 강남구 테헤란로87길 33, (삼성동)
22           서울 성동구 성수일로 77, (성수동1가) 1104, 1113호
23                    서울 강남구 강남대로 388, (역삼동) 15층
24              경기 성남시 분당구 분당수서로 477, (정자동), 16층
25               서울 강남구 삼성로 507, (삼성동) 제이에스타워 2층
26                인천 연수구 컨벤시아대로 165, (송도동) , 31층
27                인천 연수구 컨벤시아대로 165, (송도동) , 31층
28                인천 연수구 컨벤시아대로 165, (송도동) , 31층
29                인천 연수구 컨벤시아대로 165, (송도동) , 31층
30                        서울 서초구 동작대로 212, (방배동)
31                             서울시 서초구 서리풀길 29-9
32                 서울 서초구 사평대로55길 33, (반포동) 203호
33          서울 성동구 아차산로 17, (성수동1가) 서울숲엘타워 1301호
34              서울 강남구 삼성로85길 26, (대치동) V&S빌딩 7층
35                서울 마포구 월드컵로10길 5-6, (서교동) 1,2층
36                 서울 성동구 연무장길 76, (성수동2가) 1108호
37                 서울 마포구 잔다리로 39, (서교동) 로뎀빌딩 5층
38             경기도 성남시 수정구 창업로54, LH 성장기업센터 232호
39             경기도 성남시 수정구 창업로54, LH 성장기업센터 232호
40                   서울 강남구 테헤란로 501, (삼성동) 719호
41                       서울 강남구 삼성동 144-5 (에이타워)
42               서울 서초구 동작대로 230, (방배동) 화련회관 10층
43                      서울 서대문구 연세로 50, 공학원 417호
44                  서울 영등포구 의사당대로 83, (여의도동) 17층
45                  서울 영등포구 의사당대로 83, (여의도동) 17층
46    서울 강남구 테헤란로87길 36 (삼성동, 도심공항타워) 12층 델레오코리아
47                       01849 서울 노원구 동일로174길 27

                                직무  \
0                             데브옵스
1                           서버/백엔드
2                        데이터 엔지니어링
3                           서버/백엔드
4         서버/백엔드, 웹 풀스택, 데이터 엔지니어링
5                               QA
6                           서버/백엔드
7              서버/백엔드, 웹 풀스택, 데브옵스
8                        데이터 엔지니어링
9                    서버/백엔드, 웹 풀스택
10                          서버/백엔드
11                          서버/백엔드
12                    프론트엔드, 웹 풀스택
13         서버/백엔드, 웹 풀스택, 시스템/네트워크
14                          서버/백엔드
15                       데이터 엔지니어링
16          서버/백엔드, 시스템/네트워크, 데브옵스
17                          서버/백엔드
18                          서버/백엔드
19                          서버/백엔드
20       머신러닝, 인공지능(AI), 데이터 엔지니어링
21                           프론트엔드
22                   서버/백엔드, 웹 풀스택
23           머신러닝, 데이터 엔지니어링, 데브옵스
24            서버/백엔드, 프론트엔드, 웹 풀스택
25                          서버/백엔드
26                           웹 풀스택
27                          서버/백엔드
28                           웹 풀스택
29                          서버/백엔드
30                           웹 풀스택
31                          서버/백엔드
32             서버/백엔드, 프론트엔드, 개발PM
33         서버/백엔드, 게임 클라이언트, 게임 서버
34                   서버/백엔드, 웹 풀스택
35                   서버/백엔드, 웹 풀스택
36            서버/백엔드, 웹 풀스택, 게임 서버
37                    프론트엔드, 웹 풀스택
38       인공지능(AI), 데이터 엔지니어링, 데브옵스
39       인공지능(AI), 데이터 엔지니어링, 데브옵스
40     서버/백엔드, 데이터 엔지니어링, 시스템/네트워크
41             서버/백엔드, 웹 풀스택, 데브옵스
42                          서버/백엔드
43  로보틱스 미들웨어, 사물인터넷(IoT), 응용 프로그램
44                            데브옵스
45         서버/백엔드, 데이터 엔지니어링, 블록체인
46       서버/백엔드, 시스템/네트워크, 응용 프로그램
47                   서버/백엔드, 웹 풀스택

                                            이용하는 기술스택  \
0     Go\nPython\nApache Druid\nAWS DynamoDB\nAWS EC2
1   AWS EC2\nAWS ECS\nAWS Lambda\nDocker\nKubernet...
2   AWS IAM\nAWS VPC\nAWS EC2\nTerraform\nDocker\n...
3   Java\nSpring\nSpring Boot\nOracle\nMySQL\nRedi...
4   Python\nFlask\nGit\nJenkins\nuWSGI\nNginx\nDoc...
5   JIRA\nTypeScript\nNestJS\nNode.js\nPyTorch\nFl...
6   AWS CodeDeploy\nAWS CodeStar\nAWS CodeBuild\nA...
7   Kubernetes\nAWS EC2\nAzure\nGCP(Google Cloud P...
8   GCP(Google Cloud Platform)\nAzure\nAWS Glue\nA...
9   Node.js\nMySQL\nMariaDB\nMongoDB\nTypeScript\n...
10  Python\nDjango\nJava\nAWS EC2\nMySQL\nPostgreS...
11  Docker\nMySQL\nNode.js\nTypeScript\nNestJS\nTy...
12       CSS\nHTML\nJavaScript\nReactJS\nES6\nAWS EC2
13  Django\nDRF(Django REST framework)\nPython\nAW...
14                           Node.js\nAWS EC2\nNestJS
15  AWS EC2\nAWS RDS\nGCP(Google Cloud Platform)\n...
16  Docker\nGit\nMySQL\nNode.js\nRedis\nAWS CloudF...
17  Java\nSpring Boot\nMySQL\nREST API\nDocker\nBi...
18  AWS S3\nPython\nFastAPI\nAWS EC2\nAWS Lambda\n...
19  Java\nSpring Boot\nNode.js\nNestJS\nAWS EC2\nA...
20  R\nPython\nAWS EC2\nAWS Lambda\nAWS S3\nAWS Dy...
21                                   AWS RDS\nAWS EC2
22                            Python\nDjango\nAWS EC2
23     SQL\nPython\nNode.js\nAWS EC2\nGit\nJavaScript
24  Vue.js\nExpressJS\nSpring Boot\nTypeScript\nNo...
25            Django\nAWS EC2\nAWS RDS\nElasticsearch
26  ReactJS\nTypeScript\nJSX\nSass(SCSS)\nCI/CD\nG...
27  Node.js\nTypeScript\nMySQL\nCI/CD\nGitHub Acti...
28  ReactJS\nTypeScript\nJSX\nSass(SCSS)\nCI/CD\nG...
29  Node.js\nTypeScript\nMySQL\nAWS CloudFront\nAW...
30  JavaScript\nMySQL\nNode.js\nPHP\nAWS EC2\nLinu...
31  Django\nPython\nSpring\nDocker\nJavaScript\nTy...
32  TypeScript\nReactJS\nStorybook\nNode.js\nMySQL...
33  Unity\nUnreal Engine\nC#\nAWS EC2\nAWS DynamoD...
34  Java\nJenkins\nMySQL\nSpring Boot\nSpring Data...
35  AWS EC2\nMongoDB\nTypeScript\nNode.js\nNestJS\...
36  Java\nMySQL\nSpring\nNode.js\nJavaScript\nAmaz...
37  JavaScript\nReactJS\nES6\njQuery\nAWS EC2\nAWS...
38  SQL\nPython\nApache Spark\nJava\nMicrosoft Azu...
39  Python\nR\nAzure\nMachine Learning\nGCP(Google...
40      Python\nMySQL\nAWS EC2\nLinux\nRedis\nFastAPI
41  PHP\nRedis\nMySQL\nJavaScript\nGit\nDocker\nAW...
42  Node.js\nTypeScript\nREST API\nExpressJS\nMySQ...
43         Python\nDocker\nAWS EC2\nWebSocket\nWebRTC
44  AWS EC2\nAWS S3\nAWS RDS\nPython\nGit\nPostgreSQL
45  Python\nSQL\nREST API\nGit\nAWS EC2\nAWS RDS\n...
46  AWS Cloud9\nAWS EC2\nAWS RDS\nAWS S3\nCI/CD\nC...
47  Ruby on Rails\nCSS\nHTML\nJavaScript\nVue.js\n...

                                                 자격요건       직급  \
0   최소 5년 이상의 DevOps 업무 경험\n하나 이상의 개발 언어로 개발 혹은 자동...  5 ~ 10년
1   3년 내외의 백엔드 개발 경력, 또는 그에 준하는 역량을 가지신 분\nFlask, ...   1 ~ 2년
2   데이터 엔지니어 경력 2년 이상 혹은 그에 준하는 이해도가 있는 분\nSpark 및...   2 ~ 6년
3   Java, Spring Framework 기반 개발 경력 5년 이상\n주도적으로 백...  5 ~ 15년
4   【페이타랩 프로덕트팀】\n프로덕트팀은 패스오더 유저와 점주님을 연결하며 고객지향적인...  3 ~ 10년
5   3~5년의 웹 서비스 QA 경험을 갖추었거나 그에 준하는 역량을 보유하신 분\n소프...   3 ~ 5년
6   새로운 기술 및 트렌드에 대해 끊임없이 관심을 갖고 이를 활용 하시는 분\n하나의 ...   3 ~ 8년
7   Cloud 인프라 (AWS, Azure) 사용 및 SRE 경험이 3년 이상 10년 ...  3 ~ 10년
8   4년 이상의 데이터 엔지니어링 실무 경력이 있는 분\n클라우드 서비스(AWS, GC...   4 ~ 6년
9   5년 이상의 백엔드 개발 경험이 있는 분\nNode.js를 활용한 서비스 개발 및 ...  3 ~ 15년
10  • 웹에 대한 전반적인 지식, 웹 통신의 흐름, 인프라에 대한 이해\n• 제품, 서...  5 ~ 15년
11  • 소프트웨어 원리 원칙을 준수하시는 분 (SOLID, ACID)\n• Patter...  3 ~ 15년
12  프론트엔드 개발 3년 혹은 그에 준하는 역량을 보유하신 분\nReact hook을 ...   1 ~ 7년
13  Python을 현재 사랑하고 계시거나 앞으로 사랑하실 수 있어야 함\n웹에 대한 기...   3 ~ 7년
14  실무 5년차 이상 혹은 이에 준하는 역량을 보유하신 분\nTypescript + N...   3 ~ 7년
15  AWS, GCP 등 클라우드 서비스 사용에 능숙함\nnode.js 기반 playwr...  2 ~ 10년
16  Python, Java, Node.js 등을 사용한 5년 이상의 개발 경력 또는 그...  5 ~ 12년
17  Spring/SpringBoot를 이용한 웹서버 구축 경험\nRestful API ...  3 ~ 14년
18  경력\nFaceOn에서는 웹/앱 어플리케이션 개발, 운영 경험자로서의 실무 경력 3...   3 ~ 5년
19                                                NaN   5 ~ 6년
20  · 데이터사이언티스트 경력 5년 이상\n· 수학, 통계학 관련 전공 석사 학위 이상...  2 ~ 15년
21  웹 프론트엔드 개발(Front-end) 경력 2년 이상\nJavascript에 대해...   2 ~ 5년
22  웹서비스 개발 3년 이상 유 경험자\nPython, DJango를 기반으로 한 웹서...   3 ~ 5년
23  • 이공계 석사 이상의 학위를 취득하신 분\n: 졸업예정자도 지원 가능하나, 졸업증...    경력 무관
24          웹 서비스 개발 및 운영 경력 5년 이상 리드급 개발자\n나이, 성별 무관  5 ~ 10년
25  • 실무 경험 3년 이상\n• Python을 활용한 프로젝트 경험\n• 1개 이상의...  3 ~ 15년
26  웹 서비스 개발 경력이 1년 이상인 분 또는 그에 상응하는 경험이 있는 분\n스타트...   1 ~ 5년
27  웹 서비스 개발 경력이 1년 이상인 분 또는 그에 상응하는 경험이 있는 분\n한가지...   1 ~ 5년
28  웹 서비스 개발 경력이 5년 이상인 분 또는 그에 상응하는 경험이 있는 분\n컴퓨터...  5 ~ 30년
29  웹 서비스 개발 경력이 5년 이상인 분 또는 그에 상응하는 경험이 있는 분\n컴퓨터...  5 ~ 30년
30  • Flutter 개발 경력 3년 이상\n• Legacy PHP,Lalavel 웹 ...   3 ~ 6년
31  • 자신의 경험을 공유하면서 주니어 개발자들을 육성는데 관심이 있는 분\n• 메세지...  3 ~ 10년
32  웹(앱) 개발 경력 7년 이상(개발팀 리더 경력 2년 이상 포함) 또는 그에 준하는...  7 ~ 10년
33  Unity(C#) 게임 프로그래밍 경력이 3년 이상이신 분이 필요합니다.\n(또는)...  3 ~ 12년
34  Java 개발 경력 7년 이상 경험 or 실력을 보유 하신 분(필수)\nSpring...  7 ~ 13년
35  Git으로 협업하는데 어려움이 없으신 분\n불필요한 트래픽을 줄여 서버 부하를 줄여...   1 ~ 8년
36  • 3년 이상 관련 실무경험\n• Git 등 버전관리 시스템 사용 경험\n• 기술 ...  3 ~ 15년
37  React/Next.js, Typescript 를 활용한 프론트엔드 개발 경험이 있...  3 ~ 10년
38  - 컴퓨터 사이언스, 공학, 수학 또는 관련 분야의 학사 학위 또는 이와 유사한 수...    경력 무관
39          컴퓨터공학, 데이터 , AI, 수학/통계학 등 전산계열 전공자\n개발 경험    경력 무관
40  - python 기반 서비스 경험\n- 하나 이상의 RDBMS, NoSQL 사용 경...  3 ~ 10년
41  백엔드 개발경험 3년이상 또는 그에 준하는 경험이 있는 분\n함께 협업하는 사람들과...  1 ~ 10년
42  이런 분을 환영합니다! 🙂\nNode.js 숙련자 및 웹 서비스 이해가 있으신 분\...    경력 무관
43  영어로 된 문서에 대해 검색 및 독해가 익숙하신 분\n로보틱스/컴퓨터/전자공학 등 ...    경력 무관
44  - AWS 혹은 그에 준하는 클라우드 서비스를 운영해보신 경험이 있으신 분\n- 백...  3 ~ 10년
45  그래서, 아래 기준에 잘 맞는 분을 찾습니다\nHard Skills\nRDB or ...  2 ~ 15년
46  학력: 초대졸 이상\n경력: 3년 ~ 8년(클라우드 설계/운영 경험)\nCI / C...   3 ~ 8년
47  자격조건\n- 3년 이상 웹개발 경험\n- 데이터베이스에 대한 기본적 지식이 있는 ...  3 ~ 10년

                                                 우대사항  \
0   AdTech 관련 도메인 경험\n더 적은 비용으로 시스템을 운영하기 위한 비용 관리...
1   AWS, GCP, Azure와 같은 클라우드 컴퓨팅 서비스 사용 경험이 있으신 분\...
2   AWS, GCP 등 클라우드 환경에서 데이터 인프라 설계 및 운용\nMLOps 운영...
3   Jira, Confluence 등 협업툴 사용에 익숙하신 분\n아키텍처 변경에 따른...
4   【이런 분이면 더 좋아요!】\n\nMSA를 이해하고 개발 및 설계를 경험해 보신 분...
5   단순 테스트 외에 제품 사용성이나 업무 프로세스 개선에 관심이 많고 agile 기반...
6   TypeScript 기반의 NestJS 프로젝트 개발 및 고도화 경험이 있으신 분\...
7   (우대) 모니터 로깅 솔루에 대한 이해도가 있으신 분(ELK, Loki, Grafa...
8   클라우드 플랫폼을 활용해 데이터 설계, 구축, 운영 업무를 수행한 분\n대용량 데이...
9   Typescript 사용 경험 혹은 이해도가 있는 분\n컴퓨터 공학 전공자로 자료구...
10  • 컴퓨터공학과 등 관련 전공하신 분\n• 제품, 서비스 공급 기업에서  서비스 런...
11  • RFC4918 을 포함한 RFC 기반 RESTful API 구현 경험자\n   ...
12  이커머스/동영상플랫폼/학습관리시스템(LMS) 설계, 개발, 운영 경험을 보유하신 분...
13  Cloud(AWS등) 시스템 하에서 개발 경험\nPython 환경에서의 데이터 분석...
14  AWS (OpenSearch, Cognito 등) 사용 경험\nTest 코드 작성 ...
15  node.js, serverless 기반의 서버 구현에 능숙함\n브라우저 동작에 대...
16  컨테이너 기반 서비스 개발 및 운영 경험\n데이터베이스(RDBMS 또는 NoSQL,...
17  AWS 클라우드 기반 서비스 운용 및 구축 경험\n보안 및 암호화 경험\nTDD(T...
18  컴퓨터공학, 소프트웨어 엔지니어링 또는 관련 분야의 학사 또는 석사 학위 보유자\n...
19                                                NaN
20  · AWS 환경에서 데이터파이프라인 제작, 데이터베이스 구축 경험이 있으신 분\n·...
21  Back-End 개발자와의 원활한 커뮤니케이션\n웹사이트 성능 측정 및 최적화 경험...
22                              일본어 가능\n블록체인 기본 지식 보유
23  • 금융, 통계, 빅데이터 관련 연구 실적이 있으신 분\n• 데이터, 핀테크 산업 ...
24  Cloud 서비스 이용 웹서비스 및 REST API Architecture 설계 /...
25  • GIS,3D 데이터 처리 경험\n• 지오메트리 연산 경험\n• AWS 등 클라우...
26  (BE) 대규모 웹 서비스 설계 및 개발 경험이 있는 분\n(FE) 반응형웹, 웹 ...
27  대규모 웹 서비스 설계 및 개발 경험이 있는 분\n서비스를 주도적으로 개선하는 일을...
28  대규모 웹 서비스 설계 및 개발 경험이 있는 분\n반응형웹, 웹 표준을 고려한 UI...
29  대규모 웹 서비스 설계 및 개발 경험이 있는 분\n서비스를 주도적으로 개선하는 일을...
30  • React 개발 경험\n• Restful API 경험자\n• 다양한 기술 스택 ...
31  • AWS와 같은 서비스 호스팅 경험이 있으신 분\n• 빅데이터 처리 및 데이터 마...
32  영어 소통이 가능하신 분\nAI 관련 스타트업에서 개발팀을 리드해본 경험이 있으신 ...
33  게임을 좋아하고 게임 산업에 호기심이 있는 분은 저희와 문화적으로 맞을 가능성이 높...
34  금융/핀테크/커머스 시스템 개발 경험이 있으신 분\n클라우드 기반 서비스 개발 및 ...
35  Node.js, MongoDB, AWS등 서버 경험이 있으신 분\n보안관련 이슈를 ...
36  • 프로그래밍 관련 학과 전공자\n• api 설계와 비즈니스 로직 개발 경험자\n•...
37  웹 서비스 운영 경험이 있으신 분\n합리적인 사고를 기반으로 최선의 선택을 하시는,...
38  - Data Warehouse 설계, BI보고서 및 대시 보드 개발을 포함한 업계의...
39  통계적 기법을 통한 데이터 분석 역량\nR/Python 프로그래밍 및 기본적인 쿼리...
40  - 데이터&SaaS 서비스 개발 경험\n- API 연동 개발 경험\n- 정규표현식을...
41  개발을 진정 좋아하며, 본인이 맡은 기술적 챌린지를 해결해 나가는 것을 진정으로 즐...
42  이런 분은 더욱 환영합니다! 😀\n새로운 기술 습득과 지식 공유에 즐거움을 느끼시는...
43  OpenCV 개발 관련 실무 경험이 있으신 분\nRTMP, RTSP, RTP 등과 ...
44  - Cloud hosting service(especially AWS)를 깊이 사용...
45  이런 경험이 있다면 더 좋습니다\nRDB or NoSQL, 데이터베이스와 관련된 경...
46  백엔드 개발(Java) 경험\n대용량 서비스 구축/운영 경험\nMSA 구조에 대한 ...
47  우대사항\n- 웹 개발 프로세스(설계, 구현, 테스트, 배포, 운영)에 대한 이해\...

                                           해당 페이지 URL  \
0   https://career.programmers.co.kr/job_positions...
1   https://career.programmers.co.kr/job_positions...
2   https://career.programmers.co.kr/job_positions...
3   https://career.programmers.co.kr/job_positions...
4   https://career.programmers.co.kr/job_positions...
5   https://career.programmers.co.kr/job_positions...
6   https://career.programmers.co.kr/job_positions...
7   https://career.programmers.co.kr/job_positions...
8   https://career.programmers.co.kr/job_positions...
9   https://career.programmers.co.kr/job_positions...
10  https://career.programmers.co.kr/job_positions...
11  https://career.programmers.co.kr/job_positions...
12  https://career.programmers.co.kr/job_positions...
13  https://career.programmers.co.kr/job_positions...
14  https://career.programmers.co.kr/job_positions...
15  https://career.programmers.co.kr/job_positions...
16  https://career.programmers.co.kr/job_positions...
17  https://career.programmers.co.kr/job_positions...
18  https://career.programmers.co.kr/job_positions...
19  https://career.programmers.co.kr/job_positions...
20  https://career.programmers.co.kr/job_positions...
21  https://career.programmers.co.kr/job_positions...
22  https://career.programmers.co.kr/job_positions...
23  https://career.programmers.co.kr/job_positions...
24  https://career.programmers.co.kr/job_positions...
25  https://career.programmers.co.kr/job_positions...
26  https://career.programmers.co.kr/job_positions...
27  https://career.programmers.co.kr/job_positions...
28  https://career.programmers.co.kr/job_positions...
29  https://career.programmers.co.kr/job_positions...
30  https://career.programmers.co.kr/job_positions...
31  https://career.programmers.co.kr/job_positions...
32  https://career.programmers.co.kr/job_positions...
33  https://career.programmers.co.kr/job_positions...
34  https://career.programmers.co.kr/job_positions...
35  https://career.programmers.co.kr/job_positions...
36  https://career.programmers.co.kr/job_positions...
37  https://career.programmers.co.kr/job_positions...
38  https://career.programmers.co.kr/job_positions...
39  https://career.programmers.co.kr/job_positions...
40  https://career.programmers.co.kr/job_positions...
41  https://career.programmers.co.kr/job_positions...
42  https://career.programmers.co.kr/job_positions...
43  https://career.programmers.co.kr/job_positions...
44  https://career.programmers.co.kr/job_positions...
45  https://career.programmers.co.kr/job_positions...
46  https://career.programmers.co.kr/job_positions...
47  https://career.programmers.co.kr/job_positions...

                               기업 홈페이지 URL                       업종분류  \
0                    https://www.ab180.co/                        NaN
1                    https://www.ab180.co/                        NaN
2                    https://lemonbase.com      시스템ㆍ응용 소프트웨어 개발 및 공급업
3                https://www.autowini.com/                     상품 중개업
4         https://recruit.passorder.co.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
5                      https://www.lovo.ai      시스템ㆍ응용 소프트웨어 개발 및 공급업
6                      https://www.lovo.ai      시스템ㆍ응용 소프트웨어 개발 및 공급업
7       https://hanwhavision.ninehire.site           방송 및 무선 통신장비 제조업
8                 https://www.dplanex.com/             그 외 기타 정보 서비스업
9                http://balaanofficial.com                     통신 판매업
10                      https://afzima.com             그 외 기타 정보 서비스업
11                    https://www.sync.day                     통신 판매업
12               https://career.weolbu.com                그 외 기타 교육기관
13                      http://8percent.kr             시장 조사 및 여론 조사업
14                 https://www.ant-inc.co/        자동차 신품 부품 및 내장품 판매업
15                 https://forspacelab.com      시스템ㆍ응용 소프트웨어 개발 및 공급업
16                 https://forspacelab.com      시스템ㆍ응용 소프트웨어 개발 및 공급업
17                   http://ukmedia.co.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
18            https://www.faceonkorea.com/      시스템ㆍ응용 소프트웨어 개발 및 공급업
19                  https://www.chabot.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
20                      http://carvi.co.kr               기타 전자 부품 제조업
21            https://www.bbodek.com/Index                     통신 판매업
22                 https://legaltech.co.kr      시스템ㆍ응용 소프트웨어 개발 및 공급업
23              https://www.connexioh.net/      시스템ㆍ응용 소프트웨어 개발 및 공급업
24              https://www.hyundai-gs.com                        NaN
25                    https://flexity.app/      시스템ㆍ응용 소프트웨어 개발 및 공급업
26                https://www.jnpmedi.com/      시스템ㆍ응용 소프트웨어 개발 및 공급업
27                https://www.jnpmedi.com/      시스템ㆍ응용 소프트웨어 개발 및 공급업
28                https://www.jnpmedi.com/      시스템ㆍ응용 소프트웨어 개발 및 공급업
29                https://www.jnpmedi.com/      시스템ㆍ응용 소프트웨어 개발 및 공급업
30             http://www.englishegg.co.kr              서적 및 문구용품 소매업
31                    https://cnai.ai/home      시스템ㆍ응용 소프트웨어 개발 및 공급업
32  https://www.ingradient.ai/kr/index.php      시스템ㆍ응용 소프트웨어 개발 및 공급업
33                 https://www.afidev.com/     포털 및 기타 인터넷 정보 매개 서비스업
34                 https://www.twave.co.kr      시스템ㆍ응용 소프트웨어 개발 및 공급업
35                https://www.yolocorp.kr/                     상품 중개업
36               https://www.arenacast.io/      시스템ㆍ응용 소프트웨어 개발 및 공급업
37                  https://cvkorea.co.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
38                     https://coontec.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
39                     https://coontec.kr/      시스템ㆍ응용 소프트웨어 개발 및 공급업
40             https://www.attracker.shop/  기타 정보 기술 및 컴퓨터 운영 관련 서비스업
41              http://www.sellerhub.co.kr                     통신 판매업

,Unnamed: 0,기업명,사원수,주소,직무,이용하는 기술스택,자격요건,직급,우대사항,해당 페이지 URL,기업 홈페이지 URL,업종분류,설립연도,매출액
0,0,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",데브옵스,Go\nPython\nApache Druid\nAWS DynamoDB\nAWS EC2,최소 5년 이상의 DevOps 업무 경험\n하나 이상의 개발 언어로 개발 혹은 자동...,5 ~ 10년,AdTech 관련 도메인 경험\n더 적은 비용으로 시스템을 운영하기 위한 비용 관리...,https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
1,1,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",서버/백엔드,AWS EC2\nAWS ECS\nAWS Lambda\nDocker\nKubernet...,"3년 내외의 백엔드 개발 경력, 또는 그에 준하는 역량을 가지신 분\nFlask, ...",1 ~ 2년,"AWS, GCP, Azure와 같은 클라우드 컴퓨팅 서비스 사용 경험이 있으신 분\...",https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
2,2,레몬베이스,63 명,"서울 성동구 아차산로 68, (성수동2가) 11층, 12층 레몬베이스",데이터 엔지니어링,AWS IAM\nAWS VPC\nAWS EC2\nTerraform\nDocker\n...,데이터 엔지니어 경력 2년 이상 혹은 그에 준하는 이해도가 있는 분\nSpark 및...,2 ~ 6년,"AWS, GCP 등 클라우드 환경에서 데이터 인프라 설계 및 운용\nMLOps 운영...",https://career.programmers.co.kr/job_positions...,https://lemonbase.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),-원
3,3,오토위니,55 명,"서울 강남구 남부순환로 2645, 3층 (도곡동, 한독빌딩)",서버/백엔드,Java\nSpring\nSpring Boot\nOracle\nMySQL\nRedi...,"Java, Spring Framework 기반 개발 경력 5년 이상\n주도적으로 백...",5 ~ 15년,"Jira, Confluence 등 협업툴 사용에 익숙하신 분\n아키텍처 변경에 따른...",https://career.programmers.co.kr/job_positions...,https://www.autowini.com/,상품 중개업,10년 (2014년 설립),"729억5,454만원"
4,4,페이타랩,68 명,"서울 강남구 영동대로85길 34, (대치동) 6층","서버/백엔드, 웹 풀스택, 데이터 엔지니어링",Python\nFlask\nGit\nJenkins\nuWSGI\nNginx\nDoc...,【페이타랩 프로덕트팀】\n프로덕트팀은 패스오더 유저와 점주님을 연결하며 고객지향적인...,3 ~ 10년,【이런 분이면 더 좋아요!】\n\nMSA를 이해하고 개발 및 설계를 경험해 보신 분...,https://career.programmers.co.kr/job_positions...,https://recruit.passorder.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),-원

In [10]:
pro_end.head()

,Unnamed: 0,기업명,사원수,주소,직무,이용하는 기술스택,자격요건,직급,우대사항,해당 페이지 URL,기업 홈페이지 URL,업종분류,설립연도,매출액
0,0,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",데브옵스,Go\nPython\nApache Druid\nAWS DynamoDB\nAWS EC2,최소 5년 이상의 DevOps 업무 경험\n하나 이상의 개발 언어로 개발 혹은 자동...,5 ~ 10년,AdTech 관련 도메인 경험\n더 적은 비용으로 시스템을 운영하기 위한 비용 관리...,https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
1,1,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",서버/백엔드,AWS EC2\nAWS ECS\nAWS Lambda\nDocker\nKubernet...,"3년 내외의 백엔드 개발 경력, 또는 그에 준하는 역량을 가지신 분\nFlask, ...",1 ~ 2년,"AWS, GCP, Azure와 같은 클라우드 컴퓨팅 서비스 사용 경험이 있으신 분\...",https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
2,2,레몬베이스,63 명,"서울 성동구 아차산로 68, (성수동2가) 11층, 12층 레몬베이스",데이터 엔지니어링,AWS IAM\nAWS VPC\nAWS EC2\nTerraform\nDocker\n...,데이터 엔지니어 경력 2년 이상 혹은 그에 준하는 이해도가 있는 분\nSpark 및...,2 ~ 6년,"AWS, GCP 등 클라우드 환경에서 데이터 인프라 설계 및 운용\nMLOps 운영...",https://career.programmers.co.kr/job_positions...,https://lemonbase.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),-원
3,3,오토위니,55 명,"서울 강남구 남부순환로 2645, 3층 (도곡동, 한독빌딩)",서버/백엔드,Java\nSpring\nSpring Boot\nOracle\nMySQL\nRedi...,"Java, Spring Framework 기반 개발 경력 5년 이상\n주도적으로 백...",5 ~ 15년,"Jira, Confluence 등 협업툴 사용에 익숙하신 분\n아키텍처 변경에 따른...",https://career.programmers.co.kr/job_positions...,https://www.autowini.com/,상품 중개업,10년 (2014년 설립),"729억5,454만원"
4,4,페이타랩,68 명,"서울 강남구 영동대로85길 34, (대치동) 6층","서버/백엔드, 웹 풀스택, 데이터 엔지니어링",Python\nFlask\nGit\nJenkins\nuWSGI\nNginx\nDoc...,【페이타랩 프로덕트팀】\n프로덕트팀은 패스오더 유저와 점주님을 연결하며 고객지향적인...,3 ~ 10년,【이런 분이면 더 좋아요!】\n\nMSA를 이해하고 개발 및 설계를 경험해 보신 분...,https://career.programmers.co.kr/job_positions...,https://recruit.passorder.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),-원

## 2. 데이터 전처리 (pandas, numpy)
+ (1) 결측치(Null, NaN) 확인 및 처리
+ (2) 중복값 확인 및 처리
+ (3) 데이터 타입 확인 및 제거
+ (4) 데이터 타입 변경 처리 (날짜, 숫자, 범주형, 문자)

(1) 결측치(Null, NaN) 확인 및 처리

In [16]:
# Unnamed: 0 이라는 컬럼이 인덱스가 되도록 수정
import pandas as pd
pro_end = pd.read_excel(r'../EDA자료/pro_end.xlsx', index_col=0)
pro_end.head()

,기업명,사원수,주소,직무,이용하는 기술스택,자격요건,직급,우대사항,해당 페이지 URL,기업 홈페이지 URL,업종분류,설립연도,매출액
0,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",데브옵스,Go\nPython\nApache Druid\nAWS DynamoDB\nAWS EC2,최소 5년 이상의 DevOps 업무 경험\n하나 이상의 개발 언어로 개발 혹은 자동...,5 ~ 10년,AdTech 관련 도메인 경험\n더 적은 비용으로 시스템을 운영하기 위한 비용 관리...,https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
1,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",서버/백엔드,AWS EC2\nAWS ECS\nAWS Lambda\nDocker\nKubernet...,"3년 내외의 백엔드 개발 경력, 또는 그에 준하는 역량을 가지신 분\nFlask, ...",1 ~ 2년,"AWS, GCP, Azure와 같은 클라우드 컴퓨팅 서비스 사용 경험이 있으신 분\...",https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
2,레몬베이스,63 명,"서울 성동구 아차산로 68, (성수동2가) 11층, 12층 레몬베이스",데이터 엔지니어링,AWS IAM\nAWS VPC\nAWS EC2\nTerraform\nDocker\n...,데이터 엔지니어 경력 2년 이상 혹은 그에 준하는 이해도가 있는 분\nSpark 및...,2 ~ 6년,"AWS, GCP 등 클라우드 환경에서 데이터 인프라 설계 및 운용\nMLOps 운영...",https://career.programmers.co.kr/job_positions...,https://lemonbase.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),-원
3,오토위니,55 명,"서울 강남구 남부순환로 2645, 3층 (도곡동, 한독빌딩)",서버/백엔드,Java\nSpring\nSpring Boot\nOracle\nMySQL\nRedi...,"Java, Spring Framework 기반 개발 경력 5년 이상\n주도적으로 백...",5 ~ 15년,"Jira, Confluence 등 협업툴 사용에 익숙하신 분\n아키텍처 변경에 따른...",https://career.programmers.co.kr/job_positions...,https://www.autowini.com/,상품 중개업,10년 (2014년 설립),"729억5,454만원"
4,페이타랩,68 명,"서울 강남구 영동대로85길 34, (대치동) 6층","서버/백엔드, 웹 풀스택, 데이터 엔지니어링",Python\nFlask\nGit\nJenkins\nuWSGI\nNginx\nDoc...,【페이타랩 프로덕트팀】\n프로덕트팀은 패스오더 유저와 점주님을 연결하며 고객지향적인...,3 ~ 10년,【이런 분이면 더 좋아요!】\n\nMSA를 이해하고 개발 및 설계를 경험해 보신 분...,https://career.programmers.co.kr/job_positions...,https://recruit.passorder.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),-원

In [17]:
pro_end.shape

(48, 13)

In [18]:
pro_end.isna().sum()

기업명            0
사원수            0
주소             0
직무             0
이용하는 기술스택      0
자격요건           1
직급             0
우대사항           1
해당 페이지 URL     0
기업 홈페이지 URL    0
업종분류           3
설립연도           3
매출액            3
dtype: int64

In [19]:
#dropna를 활용해 결측치 제거하기
pro_end.dropna().shape

(44, 13)

In [20]:
#결측치가 있는 컬럼을 제거하기
pro_end.dropna(axis=1).shape

(48, 8)

In [21]:
#모든 데이터가 결측치인 컬럼을 제거하기
pro_end.dropna(axis=1, how='all').shape

(48, 13)

(2) 중복값 확인 및 처리

In [23]:
pro_end.columns

Index(['기업명', '사원수', '주소', '직무', '이용하는 기술스택', '자격요건', '직급', '우대사항',
       '해당 페이지 URL', '기업 홈페이지 URL', '업종분류', '설립연도', '매출액'],
      dtype='object')

In [24]:
column_headers = ['기업명', '사원수', '주소', '직무', '이용하는 기술스택', '자격요건', '직급', '우대사항',
       '해당 페이지 URL', '기업 홈페이지 URL', '업종분류', '설립연도', '매출액']
pro_end_df = pd.read_excel(r'../EDA자료/pro_end.xlsx', names=column_headers)
pro_end_df

,기업명,사원수,주소,직무,이용하는 기술스택,자격요건,직급,우대사항,해당 페이지 URL,기업 홈페이지 URL,업종분류,설립연도,매출액
0,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",데브옵스,Go\nPython\nApache Druid\nAWS DynamoDB\nAWS EC2,최소 5년 이상의 DevOps 업무 경험\n하나 이상의 개발 언어로 개발 혹은 자동...,5 ~ 10년,AdTech 관련 도메인 경험\n더 적은 비용으로 시스템을 운영하기 위한 비용 관리...,https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
1,AB180,101 명,"대한민국 서울특별시 서초구 강남대로61길 17, 강남대로61길 17",서버/백엔드,AWS EC2\nAWS ECS\nAWS Lambda\nDocker\nKubernet...,"3년 내외의 백엔드 개발 경력, 또는 그에 준하는 역량을 가지신 분\nFlask, ...",1 ~ 2년,"AWS, GCP, Azure와 같은 클라우드 컴퓨팅 서비스 사용 경험이 있으신 분\...",https://career.programmers.co.kr/job_positions...,https://www.ab180.co/,NaN,NaN,NaN
2,레몬베이스,63 명,"서울 성동구 아차산로 68, (성수동2가) 11층, 12층 레몬베이스",데이터 엔지니어링,AWS IAM\nAWS VPC\nAWS EC2\nTerraform\nDocker\n...,데이터 엔지니어 경력 2년 이상 혹은 그에 준하는 이해도가 있는 분\nSpark 및...,2 ~ 6년,"AWS, GCP 등 클라우드 환경에서 데이터 인프라 설계 및 운용\nMLOps 운영...",https://career.programmers.co.kr/job_positions...,https://lemonbase.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),-원
3,오토위니,55 명,"서울 강남구 남부순환로 2645, 3층 (도곡동, 한독빌딩)",서버/백엔드,Java\nSpring\nSpring Boot\nOracle\nMySQL\nRedi...,"Java, Spring Framework 기반 개발 경력 5년 이상\n주도적으로 백...",5 ~ 15년,"Jira, Confluence 등 협업툴 사용에 익숙하신 분\n아키텍처 변경에 따른...",https://career.programmers.co.kr/job_positions...,https://www.autowini.com/,상품 중개업,10년 (2014년 설립),"729억5,454만원"
4,페이타랩,68 명,"서울 강남구 영동대로85길 34, (대치동) 6층","서버/백엔드, 웹 풀스택, 데이터 엔지니어링",Python\nFlask\nGit\nJenkins\nuWSGI\nNginx\nDoc...,【페이타랩 프로덕트팀】\n프로덕트팀은 패스오더 유저와 점주님을 연결하며 고객지향적인...,3 ~ 10년,【이런 분이면 더 좋아요!】\n\nMSA를 이해하고 개발 및 설계를 경험해 보신 분...,https://career.programmers.co.kr/job_positions...,https://recruit.passorder.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),-원
5,로보코리아,33 명,"서울 강남구 테헤란로25길 7, (역삼동)",QA,JIRA\nTypeScript\nNestJS\nNode.js\nPyTorch\nFl...,3~5년의 웹 서비스 QA 경험을 갖추었거나 그에 준하는 역량을 보유하신 분\n소프...,3 ~ 5년,단순 테스트 외에 제품 사용성이나 업무 프로세스 개선에 관심이 많고 agile 기반...,https://career.programmers.co.kr/job_positions...,https://www.lovo.ai,시스템ㆍ응용 소프트웨어 개발 및 공급업,7년 (2017년 설립),6억882만원
6,로보코리아,33 명,"서울 강남구 테헤란로25길 7, (역삼동)",서버/백엔드,AWS CodeDeploy\nAWS CodeStar\nAWS CodeBuild\nA...,새로운 기술 및 트렌드에 대해 끊임없이 관심을 갖고 이를 활용 하시는 분\n하나의 ...,3 ~ 8년,TypeScript 기반의 NestJS 프로젝트 개발 및 고도화 경험이 있으신 분\...,https://career.programmers.co.kr/job_positions...,https://www.lovo.ai,시스템ㆍ응용 소프트웨어 개발 및 공급업,7년 (2017년 설립),6억882만원
7,한화비전,791 명,경기도 성남시 분당구 판교로319번길 6 (삼평동),"서버/백엔드, 웹 풀스택, 데브옵스",Kubernetes\nAWS EC2\nAzure\nGCP(Google Cloud P...,"Cloud 인프라 (AWS, Azure) 사용 및 SRE 경험이 3년 이상 10년 ...",3 ~ 10년,"(우대) 모니터 로깅 솔루에 대한 이해도가 있으신 분(ELK, Loki, Grafa...",https://career.programmers.co.kr/job_positions...,https://hanwhavision.ninehire.site,방송 및 무선 통신장비 제조업,6년 (2018년 설립),-원
8,디플래닉스,25 명,"서울 서초구 강남대로 465, 강남 교보타워 B동 4층",데이터 엔지니어링,GCP(Google Cloud Platform)\nAzure\nAWS Glue\nA...,"4년 이상의 데이터 엔지니어링 실무 경력이 있는 분\n클라우드 서비스(AWS, GC...",4 ~ 6년,"클라우드 플랫폼을 활용해 데이터 설계, 구축, 운영 업무를 수행한 분\n대용량 데이...",https://career.programmers.co.kr/job_positions...,https://www.dplanex.com/,그 외 기타 정보 서비스업,2년 (2022년 설립),-원
9,발란,66 명,"대한민국 서울특별시 강남구 테헤란로 217, 10층","서버/백엔드, 웹 풀스택",Node.js\nMySQL\nMariaDB\nMongoDB\nTypeScript\n...,5년 이상의 백엔드 개발 경험이 있는 분\nNode.js를 활용한 서비스 개발 및 ...,3 ~ 15년,Typescript 사용 경험 혹은 이해도가 있는 분\n컴퓨터 공학 전공자로 자료구...,https://career.programmers.co.kr/job_positions...,http://balaanofficial.com,통신 판매업,9년 (2015년 설립),"521억7,961만원"
10,헬스피디아,9 명,다산로104,서버/백엔드,Python\nDjango\nJava\nAWS EC2\nMySQL\nPostgreS...,"• 웹에 대한 전반적인 지식, 웹 통신의 흐름, 인프라에 대한 이해\n• 제품, 서...",5 ~ 15년,"• 컴퓨터공학과 등 관련 전공하신 분\n• 제품, 서비스 공급 기업에서 서비스 런...",https://career.programmers.co.kr/job_positions...,https://afzima.com,그 외 기타 정보 서비스업,3년 (2021년 설립),-원
11,플라잉캣,3 명,"서울 강남구 논현로57길 30, (도곡동)",서버/백엔드,Docker\nMySQL\nNode.js\nTypeScript\nNestJS\nTy...,"• 소프트웨어 원리 원칙을 준수하시는 분 (SOLID, ACID)\n• Patter...",3 ~ 15년,• RFC4918 을 포함한 RFC 기반 RESTful API 구현 경험자\n ...,https://career.programmers.co.kr/job_positions...,https://www.sync.day,통신 판매업,6년 (2018년 설립),"5,361만원"
12,월급쟁이부자들,84 명,"서울 서초구 사임당로 143, (서초동) 201호","프론트엔드, 웹 풀스택",CSS\nHTML\nJavaScript\nReactJS\nES6\nAWS EC2,프론트엔드 개발 3년 혹은 그에 준하는 역량을 보유하신 분\nReact hook을 ...,1 ~ 7년,"이커머스/동영상플랫폼/학습관리시스템(LMS) 설계, 개발, 운영 경험을 보유하신 분...",https://career.programmers.co.kr/job_positions...,https://career.weolbu.com,그 외 기타 교육기관,6년 (2018년 설립),"239억9,000만원"
13,에잇퍼센트,55 명,"서울특별시 영등포구 국제금융로2길 17, 13층(여의도동, 씨티플라자)","서버/백엔드, 웹 풀스택, 시스템/네트워크",Django\nDRF(Django REST framework)\nPython\nAW...,Python을 현재 사랑하고 계시거나 앞으로 사랑하실 수 있어야 함\n웹에 대한 기...,3 ~ 7년,Cloud(AWS등) 시스템 하에서 개발 경험\nPython 환경에서의 데이터 분석...,https://career.programmers.co.kr/job_positions...,http://8percent.kr,시장 조사 및 여론 조사업,9년 (2015년 설립),14억730만원
14,앤트,19 명,"서울 강남구 논현로75길 16, (역삼동)",서버/백엔드,Node.js\nAWS EC2\nNestJS,실무 5년차 이상 혹은 이에 준하는 역량을 보유하신 분\nTypescript + N...,3 ~ 7년,"AWS (OpenSearch, Cognito 등) 사용 경험\nTest 코드 작성 ...",https://career.programmers.co.kr/job_positions...,https://www.ant-inc.co/,자동차 신품 부품 및 내장품 판매업,9년 (2015년 설립),"21억3,342만원"
15,포스페이스랩,20 명,"서울 강남구 테헤란로 147, (역삼동) 3층 위멤버스클럽",데이터 엔지니어링,AWS EC2\nAWS RDS\nGCP(Google Cloud Platform)\n...,"AWS, GCP 등 클라우드 서비스 사용에 능숙함\nnode.js 기반 playwr...",2 ~ 10년,"node.js, serverless 기반의 서버 구현에 능숙함\n브라우저 동작에 대...",https://career.programmers.co.kr/job_positions...,https://forspacelab.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,5년 (2019년 설립),510만원
16,포스페이스랩,20 명,"서울 강남구 테헤란로 147, (역삼동) 3층 위멤버스클럽","서버/백엔드, 시스템/네트워크, 데브옵스",Docker\nGit\nMySQL\nNode.js\nRedis\nAWS CloudF...,"Python, Java, Node.js 등을 사용한 5년 이상의 개발 경력 또는 그...",5 ~ 12년,"컨테이너 기반 서비스 개발 및 운영 경험\n데이터베이스(RDBMS 또는 NoSQL,...",https://career.programmers.co.kr/job_positions...,https://forspacelab.com,시스템ㆍ응용 소프트웨어 개발 및 공급업,5년 (2019년 설립),510만원
17,유케이미디어,11 명,"서울 종로구 종로 51, (종로2가)",서버/백엔드,Java\nSpring Boot\nMySQL\nREST API\nDocker\nBi...,Spring/SpringBoot를 이용한 웹서버 구축 경험\nRestful API ...,3 ~ 14년,AWS 클라우드 기반 서비스 운용 및 구축 경험\n보안 및 암호화 경험\nTDD(T...,https://career.programmers.co.kr/job_positions...,http://ukmedia.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,3년 (2021년 설립),-원
18,링키스,3 명,서울특별시 강남구 도산대로 145 인우빌딩 4층 408호 (패스트파이브 신사점),서버/백엔드,AWS S3\nPython\nFastAPI\nAWS EC2\nAWS Lambda\n...,"경력\nFaceOn에서는 웹/앱 어플리케이션 개발, 운영 경험자로서의 실무 경력 3...",3 ~ 5년,"컴퓨터공학, 소프트웨어 엔지니어링 또는 관련 분야의 학사 또는 석사 학위 보유자\n...",https://career.programmers.co.kr/job_positions...,https://www.faceonkorea.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,2년 (2022년 설립),-원
19,차봇모빌리티,78 명,"대한민국 서울특별시 성동구 연무장7길 11, 플레이스캠프 성수 10층",서버/백엔드,Java\nSpring Boot\nNode.js\nNestJS\nAWS EC2\nA...,NaN,5 ~ 6년,NaN,https://career.programmers.co.kr/job_positions...,https://www.chabot.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,7년 (2017년 설립),"103억6,481만원"
20,카비,23 명,"서울 금천구 벚꽃로 244, (가산동) 벽산디지털밸리 5차 301호","머신러닝, 인공지능(AI), 데이터 엔지니어링",R\nPython\nAWS EC2\nAWS Lambda\nAWS S3\nAWS Dy...,"· 데이터사이언티스트 경력 5년 이상\n· 수학, 통계학 관련 전공 석사 학위 이상...",2 ~ 15년,"· AWS 환경에서 데이터파이프라인 제작, 데이터베이스 구축 경험이 있으신 분\n·...",https://career.programmers.co.kr/job_positions...,http://carvi.co.kr,기타 전자 부품 제조업,14년 (2010년 설립),"5,932만원"
21,뽀득,265 명,"서울 강남구 테헤란로87길 33, (삼성동)",프론트엔드,AWS RDS\nAWS EC2,웹 프론트엔드 개발(Front-end) 경력 2년 이상\nJavascript에 대해...,2 ~ 5년,Back-End 개발자와의 원활한 커뮤니케이션\n웹사이트 성능 측정 및 최적화 경험...,https://career.programmers.co.kr/job_positions...,https://www.bbodek.com/Index,통신 판매업,7년 (2017년 설립),"31억4,756만원"
22,리걸테크,27 명,"서울 성동구 성수일로 77, (성수동1가) 1104, 1113호","서버/백엔드, 웹 풀스택",Python\nDjango\nAWS EC2,"웹서비스 개발 3년 이상 유 경험자\nPython, DJango를 기반으로 한 웹서...",3 ~ 5년,일본어 가능\n블록체인 기본 지식 보유,https://career.programmers.co.kr/job_positions...,https://legaltech.co.kr,시스템ㆍ응용 소프트웨어 개발 및 공급업,9년 (2015년 설립),-원
23,코넥시오에이치,20 명,"서울 강남구 강남대로 388, (역삼동) 15층","머신러닝, 데이터 엔지니어링, 데브옵스",SQL\nPython\nNode.js\nAWS EC2\nGit\nJavaScript,"• 이공계 석사 이상의 학위를 취득하신 분\n: 졸업예정자도 지원 가능하나, 졸업증...",경력 무관,"• 금융, 통계, 빅데이터 관련 연구 실적이 있으신 분\n• 데이터, 핀테크 산업 ...",https://career.programmers.co.kr/job_positions...,https://www.connexioh.net/,시스템ㆍ응용 소프트웨어 개발 및 공급업,3년 (2021년 설립),-원
24,에이치디현대글로벌서비스,528 명,"경기 성남시 분당구 분당수서로 477, (정자동), 16층","서버/백엔드, 프론트엔드, 웹 풀스택",Vue.js\nExpressJS\nSpring Boot\nTypeScript\nNo...,"웹 서비스 개발 및 운영 경력 5년 이상 리드급 개발자\n나이, 성별 무관",5 ~ 10년,Cloud 서비스 이용 웹서비스 및 REST API Architecture 설계 /...,https://career.programmers.co.kr/job_positions...,https://www.hyundai-gs.com,NaN,NaN,NaN
25,에디트콜렉티브,15 명,"서울 강남구 삼성로 507, (삼성동) 제이에스타워 2층",서버/백엔드,Django\nAWS EC2\nAWS RDS\nElasticsearch,• 실무 경험 3년 이상\n• Python을 활용한 프로젝트 경험\n• 1개 이상의...,3 ~ 15년,"• GIS,3D 데이터 처리 경험\n• 지오메트리 연산 경험\n• AWS 등 클라우...",https://career.programmers.co.kr/job_positions...,https://flexity.app/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),842만원
26,제이앤피메디,61 명,"인천 연수구 컨벤시아대로 165, (송도동) , 31층",웹 풀스택,ReactJS\nTypeScript\nJSX\nSass(SCSS)\nCI/CD\nG...,웹 서비스 개발 경력이 1년 이상인 분 또는 그에 상응하는 경험이 있는 분\n스타트...,1 ~ 5년,"(BE) 대규모 웹 서비스 설계 및 개발 경험이 있는 분\n(FE) 반응형웹, 웹 ...",https://career.programmers.co.kr/job_positions...,https://www.jnpmedi.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),"9,797만원"
27,제이앤피메디,61 명,"인천 연수구 컨벤시아대로 165, (송도동) , 31층",서버/백엔드,Node.js\nTypeScript\nMySQL\nCI/CD\nGitHub Acti...,웹 서비스 개발 경력이 1년 이상인 분 또는 그에 상응하는 경험이 있는 분\n한가지...,1 ~ 5년,대규모 웹 서비스 설계 및 개발 경험이 있는 분\n서비스를 주도적으로 개선하는 일을...,https://career.programmers.co.kr/job_positions...,https://www.jnpmedi.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),"9,797만원"
28,제이앤피메디,61 명,"인천 연수구 컨벤시아대로 165, (송도동) , 31층",웹 풀스택,ReactJS\nTypeScript\nJSX\nSass(SCSS)\nCI/CD\nG...,웹 서비스 개발 경력이 5년 이상인 분 또는 그에 상응하는 경험이 있는 분\n컴퓨터...,5 ~ 30년,"대규모 웹 서비스 설계 및 개발 경험이 있는 분\n반응형웹, 웹 표준을 고려한 UI...",https://career.programmers.co.kr/job_positions...,https://www.jnpmedi.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),"9,797만원"
29,제이앤피메디,61 명,"인천 연수구 컨벤시아대로 165, (송도동) , 31층",서버/백엔드,Node.js\nTypeScript\nMySQL\nAWS CloudFront\nAW...,웹 서비스 개발 경력이 5년 이상인 분 또는 그에 상응하는 경험이 있는 분\n컴퓨터...,5 ~ 30년,대규모 웹 서비스 설계 및 개발 경험이 있는 분\n서비스를 주도적으로 개선하는 일을...,https://career.programmers.co.kr/job_positions...,https://www.jnpmedi.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),"9,797만원"
30,잉글리시에그,61 명,"서울 서초구 동작대로 212, (방배동)",웹 풀스택,JavaScript\nMySQL\nNode.js\nPHP\nAWS EC2\nLinu...,"• Flutter 개발 경력 3년 이상\n• Legacy PHP,Lalavel 웹 ...",3 ~ 6년,• React 개발 경험\n• Restful API 경험자\n• 다양한 기술 스택 ...,https://career.programmers.co.kr/job_positions...,http://www.englishegg.co.kr,서적 및 문구용품 소매업,15년 (2009년 설립),"185억7,483만원"
31,씨앤에이아이,48 명,서울시 서초구 서리풀길 29-9,서버/백엔드,Django\nPython\nSpring\nDocker\nJavaScript\nTy...,• 자신의 경험을 공유하면서 주니어 개발자들을 육성는데 관심이 있는 분\n• 메세지...,3 ~ 10년,• AWS와 같은 서비스 호스팅 경험이 있으신 분\n• 빅데이터 처리 및 데이터 마...,https://career.programmers.co.kr/job_positions...,https://cnai.ai/home,시스템ㆍ응용 소프트웨어 개발 및 공급업,5년 (2019년 설립),"12억2,573만원"
32,인그래디언트,4 명,"서울 서초구 사평대로55길 33, (반포동) 203호","서버/백엔드, 프론트엔드, 개발PM",TypeScript\nReactJS\nStorybook\nNode.js\nMySQL...,웹(앱) 개발 경력 7년 이상(개발팀 리더 경력 2년 이상 포함) 또는 그에 준하는...,7 ~ 10년,영어 소통이 가능하신 분\nAI 관련 스타트업에서 개발팀을 리드해본 경험이 있으신 ...,https://career.programmers.co.kr/job_positions...,https://www.ingradient.ai/kr/index.php,시스템ㆍ응용 소프트웨어 개발 및 공급업,4년 (2020년 설립),"2억5,621만원"
33,에이에프아이,22 명,"서울 성동구 아차산로 17, (성수동1가) 서울숲엘타워 1301호","서버/백엔드, 게임 클라이언트, 게임 서버",Unity\nUnreal Engine\nC#\nAWS EC2\nAWS DynamoD...,Unity(C#) 게임 프로그래밍 경력이 3년 이상이신 분이 필요합니다.\n(또는)...,3 ~ 12년,게임을 좋아하고 게임 산업에 호기심이 있는 분은 저희와 문화적으로 맞을 가능성이 높...,https://career.programmers.co.kr/job_positions...,https://www.afidev.com/,포털 및 기타 인터넷 정보 매개 서비스업,7년 (2017년 설립),"3억7,352만원"
34,티웨이브,21 명,"서울 강남구 삼성로85길 26, (대치동) V&S빌딩 7층","서버/백엔드, 웹 풀스택",Java\nJenkins\nMySQL\nSpring Boot\nSpring Data...,Java 개발 경력 7년 이상 경험 or 실력을 보유 하신 분(필수)\nSpring...,7 ~ 13년,금융/핀테크/커머스 시스템 개발 경험이 있으신 분\n클라우드 기반 서비스 개발 및 ...,https://career.programmers.co.kr/job_positions...,https://www.twave.co.kr,시스템ㆍ응용 소프트웨어 개발 및 공급업,8년 (2016년 설립),"12억3,860만원"
35,와이오엘오,37 명,"서울 마포구 월드컵로10길 5-6, (서교동) 1,2층","서버/백엔드, 웹 풀스택",AWS EC2\nMongoDB\nTypeScript\nNode.js\nNestJS\...,Git으로 협업하는데 어려움이 없으신 분\n불필요한 트래픽을 줄여 서버 부하를 줄여...,1 ~ 8년,"Node.js, MongoDB, AWS등 서버 경험이 있으신 분\n보안관련 이슈를 ...",https://career.programmers.co.kr/job_positions...,https://www.yolocorp.kr/,상품 중개업,7년 (2017년 설립),"10억2,037만원"
36,아레나캐스트,3 명,"서울 성동구 연무장길 76, (성수동2가) 1108호","서버/백엔드, 웹 풀스택, 게임 서버",Java\nMySQL\nSpring\nNode.js\nJavaScript\nAmaz...,• 3년 이상 관련 실무경험\n• Git 등 버전관리 시스템 사용 경험\n• 기술 ...,3 ~ 15년,• 프로그래밍 관련 학과 전공자\n• api 설계와 비즈니스 로직 개발 경험자\n•...,https://career.programmers.co.kr/job_positions...,https://www.arenacast.io/,시스템ㆍ응용 소프트웨어 개발 및 공급업,12년 (2012년 설립),"96억3,821만원"
37,컨비니언스,36 명,"서울 마포구 잔다리로 39, (서교동) 로뎀빌딩 5층","프론트엔드, 웹 풀스택",JavaScript\nReactJS\nES6\njQuery\nAWS EC2\nAWS...,"React/Next.js, Typescript 를 활용한 프론트엔드 개발 경험이 있...",3 ~ 10년,"웹 서비스 운영 경험이 있으신 분\n합리적인 사고를 기반으로 최선의 선택을 하시는,...",https://career.programmers.co.kr/job_positions...,https://cvkorea.co.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,11년 (2013년 설립),"105억2,327만원"
38,쿤텍,81 명,"경기도 성남시 수정구 창업로54, LH 성장기업센터 232호","인공지능(AI), 데이터 엔지니어링, 데브옵스",SQL\nPython\nApache Spark\nJava\nMicrosoft Azu...,"- 컴퓨터 사이언스, 공학, 수학 또는 관련 분야의 학사 학위 또는 이와 유사한 수...",경력 무관,"- Data Warehouse 설계, BI보고서 및 대시 보드 개발을 포함한 업계의...",https://career.programmers.co.kr/job_positions...,https://coontec.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,8년 (2016년 설립),"69억1,431만원"
39,쿤텍,81 명,"경기도 성남시 수정구 창업로54, LH 성장기업센터 232호","인공지능(AI), 데이터 엔지니어링, 데브옵스",Python\nR\nAzure\nMachine Learning\nGCP(Google...,"컴퓨터공학, 데이터 , AI, 수학/통계학 등 전산계열 전공자\n개발 경험",경력 무관,통계적 기법을 통한 데이터 분석 역량\nR/Python 프로그래밍 및 기본적인 쿼리...,https://career.programmers.co.kr/job_positions...,https://coontec.kr/,시스템ㆍ응용 소프트웨어 개발 및 공급업,8년 (2016년 설립),"69억1,431만원"
40,누벤트,18 명,"서울 강남구 테헤란로 501, (삼성동) 719호","서버/백엔드, 데이터 엔지니어링, 시스템/네트워크",Python\nMySQL\nAWS EC2\nLinux\nRedis\nFastAPI,"- python 기반 서비스 경험\n- 하나 이상의 RDBMS, NoSQL 사용 경...",3 ~ 10년,- 데이터&SaaS 서비스 개발 경험\n- API 연동 개발 경험\n- 정규표현식을...,https://career.programmers.co.kr/job_positions...,https://www.attracker.shop/,기타 정보 기술 및 컴퓨터 운영 관련 서비스업,10년 (2014년 설립),"1억2,310만원"
41,셀러허브,48 명,서울 강남구 삼성동 144-5 (에이타워),"서버/백엔드, 웹 풀스택, 데브옵스",PHP\nRedis\nMySQL\nJavaScript\nGit\nDocker\nAW...,백엔드 개발경험 3년이상 또는 그에 준하는 경험이 있는 분\n함께 협업하는 사람들과...,1 ~ 10년,"개발을 진정 좋아하며, 본인이 맡은 기술적 챌린지를 해결해 나가는 것을 진정으로 즐...",https://career.programmers.co.kr/job_positions...,http://www.sellerhub.co.kr,통신 판매업,12년 (2012년 설립),120억313만원
42,아이트럭,18 명,"서울 서초구 동작대로 230, (방배동) 화련회관 10층",서버/백엔드,Node.js\nTypeScript\nREST API\nExpressJS\nMySQ...,이런 분을 환영합니다! 🙂\nNode.js 숙련자 및 웹 서비스 이해가 있으신 분\...,경력 무관,이런 분은 더욱 환영합니다! 😀\n새로운 기술 습득과 지식 공유에 즐거움을 느끼시는...,https://career.programmers.co.kr/job_positions...,https://www.itruck.co.kr/,포털 및 기타 인터넷 정보 매개 서비스업,4년 (2020년 설립),-원
43,컨워스,8 명,"서울 서대문구 연세로 50, 공학원 417호","로보틱스 미들웨어, 사물인터넷(IoT), 응용 프로그램",Python\nDocker\nAWS EC2\nWebSocket\nWebRTC,영어로 된 문서에 대해 검색 및 독해가 익숙하신 분\n로보틱스/컴퓨터/전자공학 등 ...,경력 무관,"OpenCV 개발 관련 실무 경험이 있으신 분\nRTMP, RTSP, RTP 등과 ...",https://career.programmers.co.kr/job_positions...,http://conworth.io,그 외 기타 정보 서비스업,4년 (2020년 설립),-원
44,팀블랙버드,23 명,"서울 영등포구 의사당대로 83, (여의도동) 17층",데브옵스,AWS EC2\nAWS S3\nAWS RDS\nPython\nGit\nPostgreSQL,- AWS 혹은 그에 준하는 클라우드 서비스를 운영해보신 경험이 있으신 분\n- 백...,3 ~ 10년,- Cloud hosting service(especially AWS)를 깊이 사용...,https://career.programmers.co.kr/job_positions...,https://cryptoquant.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),"15억8,941만원"
45,팀블랙버드,23 명,"서울 영등포구 의사당대로 83, (여의도동) 17층","서버/백엔드, 데이터 엔지니어링, 블록체인",Python\nSQL\nREST API\nGit\nAWS EC2\nAWS RDS\n...,"그래서, 아래 기준에 잘 맞는 분을 찾습니다\nHard Skills\nRDB or ...",2 ~ 15년,"이런 경험이 있다면 더 좋습니다\nRDB or NoSQL, 데이터베이스와 관련된 경...",https://career.programmers.co.kr/job_positions...,https://cryptoquant.com/,시스템ㆍ응용 소프트웨어 개발 및 공급업,6년 (2018년 설립),"15억8,941만원"
46,델레오코리아,46 명,"서울 강남구 테헤란로87길 36 (삼성동, 도심공항타워) 12층 델레오코리아","서버/백엔드, 시스템/네트워크, 응용 프로그램",AWS Cloud9\nAWS EC2\nAWS RDS\nAWS S3\nCI/CD\nC...,학력: 초대졸 이상\n경력: 3년 ~ 8년(클라우드 설계/운영 경험)\nCI / C...,3 ~ 8년,백엔드 개발(Java) 경험\n대용량 서비스 구축/운영 경험\nMSA 구조에 대한 ...,https://career.programmers.co.kr/job_positions...,https://www.deleo.co.kr/#main,상품 중개업,8년 (2016년 설립),"16억9,280만원"
47,옵틱라이프,5 명,01849 서울 노원구 동일로174길 27,"서버/백엔드, 웹 풀스택",Ruby on Rails\nCSS\nHTML\nJavaScript\nVue.js\n...,자격조건\n- 3년 이상 웹개발 경험\n- 데이터베이스에 대한 기본적 지식이 있는 ...,3 ~ 10년,"우대사항\n- 웹 개발 프로세스(설계, 구현, 테스트, 배포, 운영)에 대한 이해\...",https://career.programmers.co.kr/job_positions...,http://www.opticlife.co.kr,"가방, 시계, 안경 및 기타 생활용품 도매업",6년 (2018년 설립),-원

In [25]:
# duplicated로 중복 개수 확인하기
pro_end_df.duplicated().sum()

0

In [26]:
pro_end_df.shape

(48, 13)

In [53]:
#데이터 타입 파악
pro_end_df.dtypes

기업명             object
사원수              int32
주소              object
직무              object
이용하는 기술스택       object
자격요건            object
직급              object
우대사항            object
해당 페이지 URL      object
기업 홈페이지 URL     object
업종분류            object
설립연도            object
매출액            float64
dtype: object

### '사원수', '매출액', '직급' 열의 데이터 타입을 수치형(서수형)으로 변경

사원수

In [54]:
# '사원수' 열의 데이터 타입을 문자열로 변환
pro_end_df['사원수'] = pro_end_df['사원수'].astype(str)

# '사원수' 열에서 숫자를 제외한 모든 문자를 제거하고 정수형으로 변환
pro_end_df['사원수'] = pro_end_df['사원수'].str.replace(r'\D', '', regex=True).astype(int)

# 변경된 데이터프레임 확인
print(pro_end_df['사원수'].dtype)

int32

매출액

In [57]:
import numpy as np

# 매출액 열에서 숫자를 제외한 모든 문자를 제거하고 수치형(연속형)으로 변환
pro_end_df['매출액'] = pro_end_df['매출액'].str.replace(r'[^0-9]', '', regex=True)

# 빈 문자열을 NaN 값으로 대체
pro_end_df['매출액'] = pro_end_df['매출액'].replace('', np.nan)

# NaN 값을 가진 행 삭제
pro_end_df = pro_end_df.dropna(subset=['매출액'])

# 데이터 타입을 float로 변환
pro_end_df['매출액'] = pro_end_df['매출액'].astype(float)

# 만원 단위로 변환
pro_end_df['매출액'] = pro_end_df['매출액'] / 10000

# 변경된 데이터프레임 확인
print(pro_end_df['매출액'])

2     0.000000e+00
3     7.295454e+11
4     0.000000e+00
5     6.882000e+08
6     6.882000e+08
7     0.000000e+00
8     0.000000e+00
9     5.217961e+11
10    0.000000e+00
11    5.361000e+04
12    2.399000e+11
13    1.473000e+09
14    2.133420e+10
15    5.100000e+03
16    5.100000e+03
17    0.000000e+00
18    0.000000e+00
19    1.036481e+11
20    5.932000e+04
21    3.147560e+10
22    0.000000e+00
23    0.000000e+00
25    8.420000e+03
26    9.797000e+04
27    9.797000e+04
28    9.797000e+04
29    9.797000e+04
30    1.857483e+11
31    1.225730e+10
32    2.562100e+09
33    3.735200e+09
34    1.238600e+10
35    1.020370e+10
36    9.638210e+10
37    1.052327e+11
38    6.914310e+10
39    6.914310e+10
40    1.231000e+09
41    1.203130e+10
42    0.000000e+00
43    0.000000e+00
44    1.589410e+10
45    1.589410e+10
46    1.692800e+10
47    0.000000e+00
Name: 매출액, dtype: float64

C:\Users\user\AppData\Local\Temp\ipykernel_14392\3572795574.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro_end_df['매출액'] = pro_end_df['매출액'].astype(float)
C:\Users\user\AppData\Local\Temp\ipykernel_14392\3572795574.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro_end_df['매출액'] = pro_end_df['매출액'] / 10000

직급(잠시 접어둬요.. 경력무관을 0으로 바꾸는 거에서 막힘)

In [76]:
import numpy as np

# '경력무관'을 0으로 대체
pro_end_df['직급'] = pro_end_df['직급'].replace('경력무관', 0)

# '직급' 열에서 '년'을 제거하고 최소 조건을 기준으로 수치형(서수형)으로 변경
def extract_min_years(x):
    if isinstance(x, str):
        if ' ~ ' in x:
            return float(x.split(' ~ ')[0].replace('년', '').strip())
        elif '이상' in x:
            return float(x.replace('년 이상', '').strip())
    return np.nan

pro_end_df['직급'] = pro_end_df['직급'].apply(extract_min_years)

# 변경된 데이터프레임 확인
print(pro_end_df['직급'])

2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
43   NaN
44   NaN
45   NaN
46   NaN
47   NaN
Name: 직급, dtype: float64

C:\Users\user\AppData\Local\Temp\ipykernel_14392\755905250.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro_end_df['직급'] = pro_end_df['직급'].replace('경력무관', 0)
C:\Users\user\AppData\Local\Temp\ipykernel_14392\755905250.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro_end_df['직급'] = pro_end_df['직급'].apply(extract_min_years)

주소